# frozen_string_literal: true

source "https://rubygems.org"

gem 'cucumber', '5.2'
gem 'capybara', '3.33'
gem 'rspec', '3.10'
gem 'faker', '2.14'
gem "allure-cucumber"
gem "allure-ruby-commons"
gem "allure-rspec"
gem 'allure-report-publisher', '~> 0.3.6'
gem 'report_builder', '~> 1.9'
